---
# Pushgateway Service
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: tpch-benchmark
  labels:
    app: pushgateway
spec:
  ports:
    - name: http-metrics
      port: 9091
      targetPort: 9091
  selector:
    app: pushgateway
---
# Pushgateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: tpch-benchmark
  labels:
    app: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      securityContext:
        sysctls:
        - name: fs.inotify.max_user_watches
          value: "65536"
        - name: fs.inotify.max_user_instances
          value: "512"
      containers:
      - name: pushgateway
        image: prom/pushgateway:v1.8.0
        imagePullPolicy: IfNotPresent
        args: ["--persistence.file="]
        ports:
        - containerPort: 9091
        resources:
          requests:
            cpu: "0.1"
            memory: "128Mi"
          limits:
            cpu: "0.5"
            memory: "256Mi"
